apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hic-ad-dnsupdate
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/hic-infra/hic-k8tre-extensions.git
              revision: main
              directories:
                - path: hic-ad-dnsupdate/envs/*
          - clusters:
              selector:
                matchLabels:
                  environment: "{{index .path.segments 2}}"
  template:
    metadata:
      name: "{{index .path.segments 0}}-{{.nameNormalized}}"
      annotations:
        argocd.argoproj.io/instance: "{{index .path.segments 0}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/hic-infra/hic-k8tre-extensions.git
        targetRevision: main
        path: "{{.path.path}}"
        plugin:
          name: kustomize-with-envsubst-v1.0
          env:
            - name: ENVIRONMENT
              value: "{{index .path.segments 2}}"
            - name: DOMAIN
              value: "{{index .metadata.labels \"external-domain\"}}"
      destination:
        server: "{{.server}}"
        namespace: "{{index .path.segments 0}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
