apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mssql-service.yaml
  - mssql-account-job.yaml

configMapGenerator:
  # This will be globbed by the ad service and executed there
  - name: custom-samba-start-mssql
    namespace: ad
    files:
      - mssql-spn.sh
  - name: mssql-account-job-scripts
    namespace: ad
    files:
      - provision.sh
